name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Node.js
        run: npm install -g npm@latest

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Add pnpm to PATH
        run: echo "::add-path::$HOME/.npm-packages/bin"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out # The folder where your static files are generated
          branch: gh-pages

      - name: Build and export
        run: pnpm run build && pnpm run export